export default {
  basicInfo: {
    sid: { canNull: false, reg: /^[1-9][\d]{7}$/, msg: '学号格式错误' },
    name: { canNull: false, reg: null, msg: '' },
    gender: { canNull: false, reg: null, msg: '' },
    birthPlace: { canNull: true, reg: null, msg: '' },
    ethnic: { canNull: true, reg: null, msg: '' },
    poliFace: { canNull: true, reg: null, msg: '' },
    idNum: { canNull: false, reg: /^[\d]{17}[0-9x]$/, msg: '身份证号填写有误' },
    birthDate: { canNull: true, reg: null, msg: '' },
    tel: { canNull: false, reg: /^[1-9][\d]{10}$/, msg: '电话号填写有误' },
    mail: { canNull: true, reg: /^[a-zA-Z0-9_-]+@[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+)+$/, msg: '邮箱格式有误' },
    wechat: { canNull: true, reg: null, msg: '' },
    qq: { canNull: true, reg: /^[\d]{5,11}$/, msg: 'qq格式错误' },
    degree: { canNull: true, reg: null, msg: '' },
    stuGroup: { canNull: true, reg: null, msg: '' },
    grade: { canNull: true, reg: null, msg: '' },
    major: { canNull: true, reg: null, msg: '' },
    'class': { canNull: true, reg: null, msg: '' },
    dorm: { canNull: true, reg: null, msg: '' },
    dormNumber: { canNull: true, reg: null, msg: '' },
    dormRoom: { canNull: true, reg: /^[\d]{3}$/, msg: '房间号该格式错误' },
    speciality: { canNull: true, reg: null, msg: '' },
    highSchool: { canNull: true, reg: null, msg: '' }
  },
  cadre: {
    sid: { canNull: false, reg: /^[1-9][\d]{7}$/, msg: '学号格式错误' },
    name: { canNull: false, reg: null, msg: '' },
    year: { canNull: false, reg: null, msg: '' },
    cadreClass: { canNull: false, reg: null, msg: '' },
    cadreName: { canNull: false, reg: null, msg: '' },
    cadreJiBie: { canNull: false, reg: null, msg: '' }
  },
  family: {
    sid: { canNull: false, reg: /^[1-9][\d]{7}$/, msg: '学号格式错误' },
    name: { canNull: false, reg: null, msg: '' },
    homeAddress: { canNull: true, reg: null, msg: '' },
    fatherName: { canNull: true, reg: null, msg: '' },
    fatherTel: { canNull: true, reg: null, msg: '' },
    fatherJob: { canNull: true, reg: null, msg: '' },
    motherName: { canNull: true, reg: null, msg: '' },
    motherTel: { canNull: true, reg: null, msg: '' },
    motherJob: { canNull: true, reg: null, msg: '' },
    familyAveIncome: { canNull: false, reg: /^[\d]{1,12}$/, msg: '收入格式错误' },
    isHard: { canNull: false, reg: null, msg: '' },
    hardDegree: { canNull: true, reg: null, msg: '' },
    hardFamDes: { canNull: true, reg: null, msg: '' }
  },
  paper: {
    sid: { canNull: false, reg: /^[1-9][\d]{7}$/, msg: '学号格式错误' },
    name: { canNull: false, reg: null, msg: '' },
    title: { canNull: false, reg: null, msg: '' },
    authors: { canNull: false, reg: null, msg: '' },
    journal: { canNull: false, reg: null, msg: '' },
    serialNumber: { canNull: false, reg: null, msg: '' },
    pagesRange: { canNull: false, reg: null, msg: '' },
    paperGrade: { canNull: false, reg: null, msg: '' },
    paperClass: { canNull: false, reg: null, msg: '' },
    time: { canNull: false, reg: null, msg: '' },
    insTeacher: { canNull: false, reg: null, msg: '' }
  },
  patent: {
    sid: { canNull: false, reg: /^[1-9][\d]{7}$/, msg: '学号格式错误' },
    name: { canNull: false, reg: null, msg: '' },
    patentName: { canNull: false, reg: null, msg: '' },
    'class': { canNull: false, reg: null, msg: '' },
    submitTime: { canNull: false, reg: null, msg: '' },
    approvalTime: { canNull: false, reg: null, msg: '' },
    patentRange: { canNull: false, reg: null, msg: '' },
    unit: { canNull: false, reg: null, msg: '' },
    patentNumber: { canNull: false, reg: null, msg: '' },
    creators: { canNull: false, reg: null, msg: '' }
  },
  techProject: {
    sid: { canNull: false, reg: /^[1-9][\d]{7}$/, msg: '学号格式错误' },
    name: { canNull: false, reg: null, msg: '' },
    proName: { canNull: false, reg: null, msg: '' },
    employer: { canNull: false, reg: null, msg: '' },
    money: { canNull: false, reg: /^[\d]{1,12}$/, msg: '资助金额格式错误' },
    proId: { canNull: false, reg: null, msg: '' },
    'class': { canNull: false, reg: null, msg: '' },
    teacher: { canNull: false, reg: null, msg: '' },
    proTime: { canNull: false, reg: null, msg: '' }
  }
}